FROM node:alpine 
# node version for docker 
COPY . /app
# copy evrything to app directory(i.e. the root directory)
WORKDIR /app
# work inside the app file
CMD node app.js
# run the node file inside app.js
